In [33]:
path = "C:\\Users\\Aditya Shakya\\OneDrive\\Desktop\\datasets\\ds_salaries.csv"

In [34]:
import pandas as pd
import numpy as np
df = pd.read_csv(path)
df.head()

work_year experience_level employment_type                 job_title  \
0       2023               SE              FT  Principal Data Scientist   
1       2023               MI              CT               ML Engineer   
2       2023               MI              CT               ML Engineer   
3       2023               SE              FT            Data Scientist   
4       2023               SE              FT            Data Scientist   

   salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0   80000             EUR          85847                 ES           100   
1   30000             USD          30000                 US           100   
2   25500             USD          25500                 US           100   
3  175000             USD         175000                 CA           100   
4  120000             USD         120000                 CA           100   

  company_location company_size  
0               ES            L  
1               US            S  
2               US            S  
3               CA            M  
4               CA            M

In [35]:
df.columns[df.isna().any()]

Index([], dtype='object')

In [36]:
target_df = df['salary_in_usd']

In [37]:
df.drop(['work_year','salary','salary_currency','salary_in_usd','remote_ratio'],axis = 1, inplace = True)

In [38]:
df.head()

experience_level employment_type                 job_title  \
0               SE              FT  Principal Data Scientist   
1               MI              CT               ML Engineer   
2               MI              CT               ML Engineer   
3               SE              FT            Data Scientist   
4               SE              FT            Data Scientist   

  employee_residence company_location company_size  
0                 ES               ES            L  
1                 US               US            S  
2                 US               US            S  
3                 CA               CA            M  
4                 CA               CA            M

In [39]:
from sklearn.preprocessing import LabelEncoder
le_exp = LabelEncoder()
le_emp_type = LabelEncoder()
le_job_title = LabelEncoder()
le_emp_resi = LabelEncoder()
le_com_loc = LabelEncoder()
le_com_size = LabelEncoder()

In [40]:
df['experience_level_n'] = le_exp.fit_transform(df['experience_level'])
df['employement_type_n'] = le_exp.fit_transform(df['employment_type'])
df['job_title_n'] = le_exp.fit_transform(df['job_title'])
df['employee_residence_n'] = le_exp.fit_transform(df['employee_residence'])
df['company_location_n'] = le_exp.fit_transform(df['company_location'])
df['company_size_n'] = le_exp.fit_transform(df['company_size'])

In [41]:
df.head()

experience_level employment_type                 job_title  \
0               SE              FT  Principal Data Scientist   
1               MI              CT               ML Engineer   
2               MI              CT               ML Engineer   
3               SE              FT            Data Scientist   
4               SE              FT            Data Scientist   

  employee_residence company_location company_size  experience_level_n  \
0                 ES               ES            L                   3   
1                 US               US            S                   2   
2                 US               US            S                   2   
3                 CA               CA            M                   3   
4                 CA               CA            M                   3   

   employement_type_n  job_title_n  employee_residence_n  company_location_n  \
0                   2           84                    26                  25   
1                   0           66                    75                  70   
2                   0           66                    75                  70   
3                   2           47                    11                  12   
4                   2           47                    11                  12   

   company_size_n  
0               0  
1               2  
2               2  
3               1  
4               1

In [42]:
df.drop(['experience_level',"employment_type",'job_title','employee_residence','company_location','company_size'],axis = 1, inplace = True)

In [43]:
df.head()

experience_level_n  employement_type_n  job_title_n  employee_residence_n  \
0                   3                   2           84                    26   
1                   2                   0           66                    75   
2                   2                   0           66                    75   
3                   3                   2           47                    11   
4                   3                   2           47                    11   

   company_location_n  company_size_n  
0                  25               0  
1                  70               2  
2                  70               2  
3                  12               1  
4                  12               1

In [44]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


In [47]:
X = df.values
y = target_df.values

In [49]:
f = pd.read_csv(path)

In [50]:
f.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [52]:
len(f['job_title'].unique())

93

In [53]:
df.drop(["job_title_n","employee_residence_n","company_location_n"],axis = 1,inplace = True)

In [54]:
df.head()

experience_level_n  employement_type_n  company_size_n
0                   3                   2               0
1                   2                   0               2
2                   2                   0               2
3                   3                   2               1
4                   3                   2               1

In [55]:
target_df.head()

0     85847
1     30000
2     25500
3    175000
4    120000
Name: salary_in_usd, dtype: int64

In [56]:
from sklearn.linear_model import LinearRegression
le = LinearRegression()

In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.values,target_df.values,test_size=0.2, random_state=2)

In [61]:
le.fit(X_train,y_train)

LinearRegression()

In [62]:
le.predict(X_test)

array([149784.85, 149784.85, 126978.32, 124157.93, 149784.85, 149784.85,
       126978.32, 149784.85, 149784.85,  81365.25, 152605.24, 149784.85,
        81365.25, 149784.85,  81365.25, 149784.85, 149784.85, 126978.32,
       149784.85, 149784.85, 149784.85, 129798.71, 149784.85,  84185.64,
       149784.85, 149784.85, 149784.85, 149784.85, 149784.85, 149784.85,
       149784.85,  81365.25, 149784.85, 126978.32, 152605.24, 149784.85,
        84185.64, 126978.32, 129798.71, 149784.85, 126978.32, 149784.85,
       149784.85, 126978.32, 149784.85, 149784.85, 149784.85, 126978.32,
       126978.32, 149784.85, 149784.85, 104171.79, 149784.85, 149784.85,
       149784.85, 149784.85, 126978.32, 149784.85, 149784.85, 149784.85,
       149784.85, 126978.32, 152605.24, 152605.24,  81365.25, 149784.85,
       149784.85, 126978.32, 149784.85, 149784.85, 149784.85, 126978.32,
       135640.69, 104171.79, 106992.18, 149784.85,  81365.25, 149784.85,
       149784.85, 149784.85, 149784.85, 149784.85, 

In [63]:
le.score(X_test,y_test)

0.11142549860227557

In [64]:
le.predict([[3,2,0]])

array([152605.24])

In [65]:
X_train

array([[2, 2, 1],
       [3, 2, 1],
       [0, 2, 1],
       ...,
       [3, 2, 1],
       [3, 2, 1],
       [2, 2, 1]])

In [66]:
y_train

array([141300, 153600,  22892, ...,  99000, 129300,  61566], dtype=int64)

In [71]:
from sklearn import preprocessing
# normalize the data attributes
target_df_norm = preprocessing.scale(target_df.values)


In [72]:
from sklearn.linear_model import LinearRegression
le = LinearRegression()

In [75]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.values,target_df_norm,test_size=0.2, random_state=2)

In [76]:
y_train

array([ 0.06,  0.25, -1.82, ..., -0.61, -0.13, -1.21])

In [77]:
le.fit(X_train,y_train)

LinearRegression()

In [78]:
le.predict(X_test)

array([ 0.19,  0.19, -0.17, -0.21,  0.19,  0.19, -0.17,  0.19,  0.19,
       -0.89,  0.24,  0.19, -0.89,  0.19, -0.89,  0.19,  0.19, -0.17,
        0.19,  0.19,  0.19, -0.12,  0.19, -0.85,  0.19,  0.19,  0.19,
        0.19,  0.19,  0.19,  0.19, -0.89,  0.19, -0.17,  0.24,  0.19,
       -0.85, -0.17, -0.12,  0.19, -0.17,  0.19,  0.19, -0.17,  0.19,
        0.19,  0.19, -0.17, -0.17,  0.19,  0.19, -0.53,  0.19,  0.19,
        0.19,  0.19, -0.17,  0.19,  0.19,  0.19,  0.19, -0.17,  0.24,
        0.24, -0.89,  0.19,  0.19, -0.17,  0.19,  0.19,  0.19, -0.17,
       -0.03, -0.53, -0.49,  0.19, -0.89,  0.19,  0.19,  0.19,  0.19,
        0.19,  0.19,  0.19,  0.19, -0.17, -0.89,  0.15,  0.19,  0.19,
        0.24, -0.85, -0.17,  0.19, -0.17,  0.19, -0.89, -0.21,  0.19,
       -0.17,  0.24, -0.17,  0.19,  0.19, -0.85, -0.17,  0.19,  0.19,
        0.19, -0.17,  0.19,  0.19,  0.19, -0.12,  0.19,  0.19,  0.19,
       -0.89,  0.19,  0.19,  0.19,  0.19, -0.17,  0.19,  0.19,  0.19,
       -0.17,  0.19,

In [79]:
le.score(X_test,y_test)

0.1114254986022758